import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'ru' | 'ja' | 'ko' | 'tr';

export const LANGUAGE_NAMES: Record<Language, string> = {
  en: 'English',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  it: 'Italiano',
  pt: 'Português',
  ru: 'Русский',
  ja: '日本語',
  ko: '한국어',
  tr: 'Türkçe',
};

export interface Translations {
  // Navigation
  play: string;
  leaderboard: string;
  missions: string;
  settings: string;
  back: string;
  // Game
  score: string;
  level: string;
  lines: string;
  combo: string;
  time: string;
  moves: string;
  paused: string;
  gameOver: string;
  youWin: string;
  restart: string;
  menu: string;
  resume: string;
  // Modes
  selectMode: string;
  classic: string;
  timeAttack: string;
  endless: string;
  challenge: string;
  puzzle: string;
  insanity: string;
  mirror: string;
  mirrorMode: string;
  gravityShift: string;
  comboRush: string;
  // Settings
  theme: string;
  language: string;
  sound: string;
  audio: string;
  music: string;
  mute: string;
  unmute: string;
  // Leaderboard
  rank: string;
  player: string;
  date: string;
  noScores: string;
  submitScore: string;
  enterName: string;
  // Missions
  missionsTitle: string;
  progress: string;
  completed: string;
  reward: string;
  // Game Over
  finalScore: string;
  linesCleared: string;
  playAgain: string;
  // Footer
  privacyPolicy: string;
  builtWith: string;
}

export const TRANSLATIONS: Record<Language, Translations> = {
  en: {
    play: 'Play',
    leaderboard: 'Leaderboard',
    missions: 'Missions',
    settings: 'Settings',
    back: 'Back',
    score: 'Score',
    level: 'Level',
    lines: 'Lines',
    combo: 'Combo',
    time: 'Time',
    moves: 'Moves',
    paused: 'Pause',
    gameOver: 'Game Over',
    youWin: 'You Win!',
    restart: 'Restart',
    menu: 'Menu',
    resume: 'Resume',
    selectMode: 'Select Mode',
    classic: 'Classic',
    timeAttack: 'Time Attack',
    endless: 'Endless',
    challenge: 'Challenge',
    puzzle: 'Puzzle',
    insanity: 'Insanity',
    mirror: 'Mirror Mode',
    mirrorMode: 'Mirror Mode',
    gravityShift: 'Gravity Shift',
    comboRush: 'Combo Rush',
    theme: 'Theme',
    language: 'Language',
    sound: 'Sound',
    audio: 'Audio',
    music: 'Music',
    mute: 'Mute',
    unmute: 'Unmute',
    rank: 'Rank',
    player: 'Player',
    date: 'Date',
    noScores: 'No scores yet. Be the first!',
    submitScore: 'Submit Score',
    enterName: 'Enter your name',
    missionsTitle: 'Missions',
    progress: 'Progress',
    completed: 'Completed',
    reward: 'Reward',
    finalScore: 'Final Score',
    linesCleared: 'Lines Cleared',
    playAgain: 'Play Again',
    privacyPolicy: 'Privacy Policy',
    builtWith: 'Built with',
  },
  es: {
    play: 'Jugar',
    leaderboard: 'Clasificación',
    missions: 'Misiones',
    settings: 'Ajustes',
    back: 'Atrás',
    score: 'Puntuación',
    level: 'Nivel',
    lines: 'Líneas',
    combo: 'Combo',
    time: 'Tiempo',
    moves: 'Movimientos',
    paused: 'Pausar',
    gameOver: 'Fin del Juego',
    youWin: '¡Ganaste!',
    restart: 'Reiniciar',
    menu: 'Menú',
    resume: 'Continuar',
    selectMode: 'Seleccionar Modo',
    classic: 'Clásico',
    timeAttack: 'Contrarreloj',
    endless: 'Sin Fin',
    challenge: 'Desafío',
    puzzle: 'Puzzle',
    insanity: 'Locura',
    mirror: 'Modo Espejo',
    mirrorMode: 'Modo Espejo',
    gravityShift: 'Cambio de Gravedad',
    comboRush: 'Combo Rush',
    theme: 'Tema',
    language: 'Idioma',
    sound: 'Sonido',
    audio: 'Audio',
    music: 'Música',
    mute: 'Silenciar',
    unmute: 'Activar Sonido',
    rank: 'Rango',
    player: 'Jugador',
    date: 'Fecha',
    noScores: 'Sin puntuaciones. ¡Sé el primero!',
    submitScore: 'Enviar Puntuación',
    enterName: 'Ingresa tu nombre',
    missionsTitle: 'Misiones',
    progress: 'Progreso',
    completed: 'Completado',
    reward: 'Recompensa',
    finalScore: 'Puntuación Final',
    linesCleared: 'Líneas Eliminadas',
    playAgain: 'Jugar de Nuevo',
    privacyPolicy: 'Política de Privacidad',
    builtWith: 'Construido con',
  },
  fr: {
    play: 'Jouer',
    leaderboard: 'Classement',
    missions: 'Missions',
    settings: 'Paramètres',
    back: 'Retour',
    score: 'Score',
    level: 'Niveau',
    lines: 'Lignes',
    combo: 'Combo',
    time: 'Temps',
    moves: 'Mouvements',
    paused: 'Pause',
    gameOver: 'Partie Terminée',
    youWin: 'Vous Gagnez!',
    restart: 'Recommencer',
    menu: 'Menu',
    resume: 'Reprendre',
    selectMode: 'Choisir le Mode',
    classic: 'Classique',
    timeAttack: 'Contre la Montre',
    endless: 'Sans Fin',
    challenge: 'Défi',
    puzzle: 'Puzzle',
    insanity: 'Folie',
    mirror: 'Mode Miroir',
    mirrorMode: 'Mode Miroir',
    gravityShift: 'Changement de Gravité',
    comboRush: 'Combo Rush',
    theme: 'Thème',
    language: 'Langue',
    sound: 'Son',
    audio: 'Audio',
    music: 'Musique',
    mute: 'Muet',
    unmute: 'Activer le Son',
    rank: 'Rang',
    player: 'Joueur',
    date: 'Date',
    noScores: 'Pas encore de scores. Soyez le premier!',
    submitScore: 'Soumettre le Score',
    enterName: 'Entrez votre nom',
    missionsTitle: 'Missions',
    progress: 'Progrès',
    completed: 'Terminé',
    reward: 'Récompense',
    finalScore: 'Score Final',
    linesCleared: 'Lignes Effacées',
    playAgain: 'Rejouer',
    privacyPolicy: 'Politique de Confidentialité',
    builtWith: 'Construit avec',
  },
  de: {
    play: 'Spielen',
    leaderboard: 'Bestenliste',
    missions: 'Missionen',
    settings: 'Einstellungen',
    back: 'Zurück',
    score: 'Punkte',
    level: 'Level',
    lines: 'Linien',
    combo: 'Kombo',
    time: 'Zeit',
    moves: 'Züge',
    paused: 'Pause',
    gameOver: 'Spiel Vorbei',
    youWin: 'Du Gewinnst!',
    restart: 'Neustart',
    menu: 'Menü',
    resume: 'Fortsetzen',
    selectMode: 'Modus Wählen',
    classic: 'Klassisch',
    timeAttack: 'Zeitangriff',
    endless: 'Endlos',
    challenge: 'Herausforderung',
    puzzle: 'Puzzle',
    insanity: 'Wahnsinn',
    mirror: 'Spiegelmodus',
    mirrorMode: 'Spiegelmodus',
    gravityShift: 'Gravitationswechsel',
    comboRush: 'Kombo Rush',
    theme: 'Thema',
    language: 'Sprache',
    sound: 'Ton',
    audio: 'Audio',
    music: 'Musik',
    mute: 'Stumm',
    unmute: 'Ton An',
    rank: 'Rang',
    player: 'Spieler',
    date: 'Datum',
    noScores: 'Noch keine Punkte. Sei der Erste!',
    submitScore: 'Punkte Einreichen',
    enterName: 'Gib deinen Namen ein',
    missionsTitle: 'Missionen',
    progress: 'Fortschritt',
    completed: 'Abgeschlossen',
    reward: 'Belohnung',
    finalScore: 'Endpunktzahl',
    linesCleared: 'Linien Gelöscht',
    playAgain: 'Nochmal Spielen',
    privacyPolicy: 'Datenschutzrichtlinie',
    builtWith: 'Gebaut mit',
  },
  it: {
    play: 'Gioca',
    leaderboard: 'Classifica',
    missions: 'Missioni',
    settings: 'Impostazioni',
    back: 'Indietro',
    score: 'Punteggio',
    level: 'Livello',
    lines: 'Linee',
    combo: 'Combo',
    time: 'Tempo',
    moves: 'Mosse',
    paused: 'Pausa',
    gameOver: 'Partita Finita',
    youWin: 'Hai Vinto!',
    restart: 'Ricomincia',
    menu: 'Menu',
    resume: 'Riprendi',
    selectMode: 'Seleziona Modalità',
    classic: 'Classico',
    timeAttack: 'Attacco a Tempo',
    endless: 'Infinito',
    challenge: 'Sfida',
    puzzle: 'Puzzle',
    insanity: 'Follia',
    mirror: 'Modalità Specchio',
    mirrorMode: 'Modalità Specchio',
    gravityShift: 'Cambio Gravità',
    comboRush: 'Combo Rush',
    theme: 'Tema',
    language: 'Lingua',
    sound: 'Suono',
    audio: 'Audio',
    music: 'Musica',
    mute: 'Muto',
    unmute: 'Attiva Suono',
    rank: 'Posizione',
    player: 'Giocatore',
    date: 'Data',
    noScores: 'Nessun punteggio. Sii il primo!',
    submitScore: 'Invia Punteggio',
    enterName: 'Inserisci il tuo nome',
    missionsTitle: 'Missioni',
    progress: 'Progresso',
    completed: 'Completato',
    reward: 'Ricompensa',
    finalScore: 'Punteggio Finale',
    linesCleared: 'Linee Cancellate',
    playAgain: 'Gioca Ancora',
    privacyPolicy: 'Informativa sulla Privacy',
    builtWith: 'Costruito con',
  },
  pt: {
    play: 'Jogar',
    leaderboard: 'Classificação',
    missions: 'Missões',
    settings: 'Configurações',
    back: 'Voltar',
    score: 'Pontuação',
    level: 'Nível',
    lines: 'Linhas',
    combo: 'Combo',
    time: 'Tempo',
    moves: 'Movimentos',
    paused: 'Pausar',
    gameOver: 'Fim de Jogo',
    youWin: 'Você Ganhou!',
    restart: 'Reiniciar',
    menu: 'Menu',
    resume: 'Continuar',
    selectMode: 'Selecionar Modo',
    classic: 'Clássico',
    timeAttack: 'Contra o Tempo',
    endless: 'Infinito',
    challenge: 'Desafio',
    puzzle: 'Puzzle',
    insanity: 'Insanidade',
    mirror: 'Modo Espelho',
    mirrorMode: 'Modo Espelho',
    gravityShift: 'Mudança de Gravidade',
    comboRush: 'Combo Rush',
    theme: 'Tema',
    language: 'Idioma',
    sound: 'Som',
    audio: 'Áudio',
    music: 'Música',
    mute: 'Silenciar',
    unmute: 'Ativar Som',
    rank: 'Posição',
    player: 'Jogador',
    date: 'Data',
    noScores: 'Sem pontuações. Seja o primeiro!',
    submitScore: 'Enviar Pontuação',
    enterName: 'Digite seu nome',
    missionsTitle: 'Missões',
    progress: 'Progresso',
    completed: 'Concluído',
    reward: 'Recompensa',
    finalScore: 'Pontuação Final',
    linesCleared: 'Linhas Eliminadas',
    playAgain: 'Jogar Novamente',
    privacyPolicy: 'Política de Privacidade',
    builtWith: 'Construído com',
  },
  ru: {
    play: 'Играть',
    leaderboard: 'Рейтинг',
    missions: 'Миссии',
    settings: 'Настройки',
    back: 'Назад',
    score: 'Счёт',
    level: 'Уровень',
    lines: 'Линии',
    combo: 'Комбо',
    time: 'Время',
    moves: 'Ходы',
    paused: 'Пауза',
    gameOver: 'Игра Окончена',
    youWin: 'Вы Победили!',
    restart: 'Перезапуск',
    menu: 'Меню',
    resume: 'Продолжить',
    selectMode: 'Выбор Режима',
    classic: 'Классика',
    timeAttack: 'На Время',
    endless: 'Бесконечный',
    challenge: 'Испытание',
    puzzle: 'Головоломка',
    insanity: 'Безумие',
    mirror: 'Зеркальный Режим',
    mirrorMode: 'Зеркальный Режим',
    gravityShift: 'Смена Гравитации',
    comboRush: 'Комбо Раш',
    theme: 'Тема',
    language: 'Язык',
    sound: 'Звук',
    audio: 'Аудио',
    music: 'Музыка',
    mute: 'Без Звука',
    unmute: 'Включить Звук',
    rank: 'Ранг',
    player: 'Игрок',
    date: 'Дата',
    noScores: 'Нет очков. Будьте первым!',
    submitScore: 'Отправить Счёт',
    enterName: 'Введите ваше имя',
    missionsTitle: 'Миссии',
    progress: 'Прогресс',
    completed: 'Завершено',
    reward: 'Награда',
    finalScore: 'Итоговый Счёт',
    linesCleared: 'Линий Очищено',
    playAgain: 'Играть Снова',
    privacyPolicy: 'Политика Конфиденциальности',
    builtWith: 'Создано с',
  },
  ja: {
    play: 'プレイ',
    leaderboard: 'ランキング',
    missions: 'ミッション',
    settings: '設定',
    back: '戻る',
    score: 'スコア',
    level: 'レベル',
    lines: 'ライン',
    combo: 'コンボ',
    time: '時間',
    moves: '手数',
    paused: '一時停止',
    gameOver: 'ゲームオーバー',
    youWin: '勝利！',
    restart: 'リスタート',
    menu: 'メニュー',
    resume: '再開',
    selectMode: 'モード選択',
    classic: 'クラシック',
    timeAttack: 'タイムアタック',
    endless: 'エンドレス',
    challenge: 'チャレンジ',
    puzzle: 'パズル',
    insanity: 'インサニティ',
    mirror: 'ミラーモード',
    mirrorMode: 'ミラーモード',
    gravityShift: '重力シフト',
    comboRush: 'コンボラッシュ',
    theme: 'テーマ',
    language: '言語',
    sound: 'サウンド',
    audio: 'オーディオ',
    music: '音楽',
    mute: 'ミュート',
    unmute: 'ミュート解除',
    rank: 'ランク',
    player: 'プレイヤー',
    date: '日付',
    noScores: 'スコアなし。最初になろう！',
    submitScore: 'スコア送信',
    enterName: '名前を入力',
    missionsTitle: 'ミッション',
    progress: '進捗',
    completed: '完了',
    reward: '報酬',
    finalScore: '最終スコア',
    linesCleared: 'クリアライン',
    playAgain: 'もう一度プレイ',
    privacyPolicy: 'プライバシーポリシー',
    builtWith: '制作',
  },
  ko: {
    play: '플레이',
    leaderboard: '리더보드',
    missions: '미션',
    settings: '설정',
    back: '뒤로',
    score: '점수',
    level: '레벨',
    lines: '라인',
    combo: '콤보',
    time: '시간',
    moves: '이동',
    paused: '일시정지',
    gameOver: '게임 오버',
    youWin: '승리!',
    restart: '재시작',
    menu: '메뉴',
    resume: '계속',
    selectMode: '모드 선택',
    classic: '클래식',
    timeAttack: '타임 어택',
    endless: '무한',
    challenge: '챌린지',
    puzzle: '퍼즐',
    insanity: '인새니티',
    mirror: '미러 모드',
    mirrorMode: '미러 모드',
    gravityShift: '중력 변환',
    comboRush: '콤보 러시',
    theme: '테마',
    language: '언어',
    sound: '사운드',
    audio: '오디오',
    music: '음악',
    mute: '음소거',
    unmute: '음소거 해제',
    rank: '순위',
    player: '플레이어',
    date: '날짜',
    noScores: '점수 없음. 첫 번째가 되세요!',
    submitScore: '점수 제출',
    enterName: '이름을 입력하세요',
    missionsTitle: '미션',
    progress: '진행',
    completed: '완료',
    reward: '보상',
    finalScore: '최종 점수',
    linesCleared: '클리어 라인',
    playAgain: '다시 플레이',
    privacyPolicy: '개인정보 처리방침',
    builtWith: '제작',
  },
  tr: {
    play: 'Oyna',
    leaderboard: 'Liderlik Tablosu',
    missions: 'Görevler',
    settings: 'Ayarlar',
    back: 'Geri',
    score: 'Puan',
    level: 'Seviye',
    lines: 'Satır',
    combo: 'Kombo',
    time: 'Süre',
    moves: 'Hamle',
    paused: 'Duraklat',
    gameOver: 'Oyun Bitti',
    youWin: 'Kazandın!',
    restart: 'Yeniden Başlat',
    menu: 'Menü',
    resume: 'Devam Et',
    selectMode: 'Mod Seç',
    classic: 'Klasik',
    timeAttack: 'Zaman Saldırısı',
    endless: 'Sonsuz',
    challenge: 'Meydan Okuma',
    puzzle: 'Bulmaca',
    insanity: 'Çılgınlık',
    mirror: 'Ayna Modu',
    mirrorMode: 'Ayna Modu',
    gravityShift: 'Yerçekimi Değişimi',
    comboRush: 'Kombo Koşusu',
    theme: 'Tema',
    language: 'Dil',
    sound: 'Ses',
    audio: 'Ses',
    music: 'Müzik',
    mute: 'Sessiz',
    unmute: 'Sesi Aç',
    rank: 'Sıra',
    player: 'Oyuncu',
    date: 'Tarih',
    noScores: 'Henüz puan yok. İlk sen ol!',
    submitScore: 'Puan Gönder',
    enterName: 'Adını gir',
    missionsTitle: 'Görevler',
    progress: 'İlerleme',
    completed: 'Tamamlandı',
    reward: 'Ödül',
    finalScore: 'Son Puan',
    linesCleared: 'Temizlenen Satırlar',
    playAgain: 'Tekrar Oyna',
    privacyPolicy: 'Gizlilik Politikası',
    builtWith: 'ile yapıldı',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
  allLanguages: Language[];
}

const ALL_LANGUAGES: Language[] = ['en', 'es', 'fr', 'de', 'it', 'pt', 'ru', 'ja', 'ko', 'tr'];

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: TRANSLATIONS.en,
  allLanguages: ALL_LANGUAGES,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('tetrisverse-language') as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('tetrisverse-language', lang);
  };

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage,
      t: TRANSLATIONS[language],
      allLanguages: ALL_LANGUAGES,
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
