/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ScoreEntry = IDL.Record({
  'score' : IDL.Nat,
  'timestamp' : Time,
  'playerName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMission' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'getAllScores' : IDL.Func([IDL.Text], [IDL.Vec(ScoreEntry)], ['query']),
  'getMissionReward' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], ['query']),
  'getTopScores' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(ScoreEntry)],
      ['query'],
    ),
  'isMissionCompleted' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], ['query']),
  'submitScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updateMissionProgress' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ScoreEntry = IDL.Record({
    'score' : IDL.Nat,
    'timestamp' : Time,
    'playerName' : IDL.Text,
  });
  
  return IDL.Service({
    'addMission' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'getAllScores' : IDL.Func([IDL.Text], [IDL.Vec(ScoreEntry)], ['query']),
    'getMissionReward' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], ['query']),
    'getTopScores' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(ScoreEntry)],
        ['query'],
      ),
    'isMissionCompleted' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], ['query']),
    'submitScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updateMissionProgress' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };